import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="text-center uppercase py-[3.75rem]">
          <Link href="/">
            <h1>
              <span className="text-5xl">Just Add</span>
              <br />
              <span className="text-7xl font-extrabold">Marmite</span>
            </h1>
          </Link>
          <div className="text-3xl">Spread The Joy</div>
        </header>
        <main className="max-w-[75rem] mx-auto pb-20">{children}</main>
        <footer className="bg-black text-gray-400 p-16 text-center text-2xl">
          Copyright 2021 Just Add Marmite ❤
        </footer>
      </body>
    </html>
  );
}
